version: 100.4.0-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    msbuild /t:restore src/Esri.ArcGISRuntime.Toolkit.sln
    
    msbuild /t:restore src/Esri.ArcGISRuntime.Toolkit.sln
build:
  project: src/Esri.ArcGISRuntime.Toolkit.sln
  verbosity: minimal
artifacts:
- path: .\Output\NuGet\Release\*.nupkg
  name: NuGet
